#!/bin/sh
cmake -B build  -DENABLE_AEC=ON  -DENABLE_AECM=ON   -DENABLE_UNIT_TESTS=OFF  -DENABLE_LDAP=OFF   -DENABLE_MKV=OFF  -DENABLE_VIDEO=ON -DENABLE_ADVANCED_IM=OFF -DENABLE_ZRTP=OFF -DENABLE_DB_STORAGE=OFF -DENABLE_VCARD=OFF -DENABLE_OPUS=NO  -DENABLE_VPX=ON  -DENABLE_FFMPEG=ON   -DENABLE_OPENH264=ON -DENABLE_NON_FREE_CODECS=ON
 

